### PR TITLE
Compile sardana 3.0.4dev1 (a687970)

### LINKED ISSUE #1: Enable dev release
Hi @reszelaz and @cpascual!

At MAX IV, we'd like to have some dev release build (from the develop branch).

This is possible to do on conda-forge by creating a `dev` branch. See
https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

If that sounds ok to you, I'll create a "dev" branch and make a PR.

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fix #1

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
This PR is to create a dev release of Sardana according to https://conda-forge.org/docs/maintainer/knowledge_base.html#creating-a-pre-release-build

Only `dev` and `rc` labels shall be used (not `alpha` and `beta`) for the channel, but my understanding is that we could use alpha for the package version: `3.0.4a1` (following https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#version-ordering). I chose to use `3.0.4dev1` to keep the same as the label but I don't have a very strong opinion about that.

**Comment by cpascual** [comment]
>  I chose to use 3.0.4dev1 to keep the same as the label but I don't have a very strong opinion about that.

"dev" is actually a better description than "alpha" for what we do. 

But one note: AFAIK, the [python version conventions](https://www.python.org/dev/peps/pep-0440/) require development releases to use a leading dot  (i.e. it should be `3.0.4.dev1`, not `3.0.4dev1`) , whereas for alpha and beta version, the dot is not used (`3.0.4a1`)

**Comment by beenje** [comment]
> But one note: AFAIK, the [python version conventions](https://www.python.org/dev/peps/pep-0440/) require development releases to use a leading dot (i.e. it should be `3.0.4.dev1`, not `3.0.4dev1`) , whereas for alpha and beta version, the dot is not used (`3.0.4a1`)

You are right! Thanks. I've been confused by the examples in the [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#predictable-version-ordering) speaking about inserting a 0 before string...

```
< 1.1.0dev1  # special case ``dev``
== 1.1.dev1   # 0 is inserted before string
```

I changed the version the `3.0.4.dev1`.

**Review by cpascual — APPROVED** [review]

**Pull request merged**
